INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ACTIVATED) VALUES ('admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', '099999999', 1);
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ACTIVATED) VALUES ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', '099999999', 1);
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, ACTIVATED) VALUES ('disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', '099999999', 0);

INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_SPECIAL_USER');

INSERT INTO USER_AUTHORITY (PK_USER, NAME) VALUES (1, 'ROLE_SPECIAL_USER');
INSERT INTO USER_AUTHORITY (PK_USER, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (PK_USER, NAME) VALUES (3, 'ROLE_USER');

INSERT INTO DOCTOR (PK_USER, BIOGRAPHY) VALUES (1, 'Zavrsio Medicinu');
INSERT INTO PATIENT (PK_USER, DIAGNOSIS) VALUES (2, 'Bolestan');

INSERT INTO BUSINESS_CATEGORY (NAME, decription) VALUES ('DJECA', 'opis');
INSERT INTO BUSINESS_CATEGORY (NAME, decription) VALUES ('ODRASLI', 'opis');
INSERT INTO BUSINESS_CATEGORY (NAME, decription) VALUES ('MLADI', 'opis');

INSERT INTO BUSINESS_SERVICE (NAME, DESCRIPTION, FK_CATEGORY, PRICE) VALUES ('Psihološko savjetovanje', 'opis1', 1, 10);
INSERT INTO BUSINESS_SERVICE (NAME, DESCRIPTION, FK_CATEGORY, PRICE) VALUES ('Psihološko savjetovanje', 'opis1', 2, 10.34);
INSERT INTO BUSINESS_SERVICE (NAME, DESCRIPTION, FK_CATEGORY, PRICE) VALUES ('terapija', 'opis2', 1, 10000.30);

INSERT INTO TERMIN (TERMIN_START, TERMIN_END, DESCRIPTION) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL 1 HOUR, 'Termin');

INSERT INTO REVIEW (GRADE, FK_PATIENT, FK_DOCTOR, DESCRIPTION) VALUES (5, 2, 1, 'Dobar doktor');

INSERT INTO MEETING (DESCRIPTION, MEETING_TYPE, FK_SERVICE, FK_DOCTOR, FK_PATIENT, FK_TERMIN) VALUES ('1. Sastanak', 'UZIVO', 1, 1, 2, 1);

